# This file contains the base common configurations for running pytest tavern tests in a production environment.
# It is statically generated because we anticipate the same settings for all CT test containers that inherit from it.
name: tavern_global_configuration
description: common configuration for all tavern invocations
variables:
  verify: false
  bss_base_url: http://localhost:8080/apis/bss
  capmc_base_url: http://localhost:8080/apis/capmc
  fas_base_url: http://localhost:8080/apis/fas/v1
  hbtd_base_url: http://localhost:8080/apis/hbtd # TODO
  hmnfd_base_url: http://localhost:8080/apis/hmnfd # TODO
  hsm_base_url: http://localhost:8080/apis/smd
  pcs_base_url: http://localhost:8080/apis/power-control # TODO
  reds_base_url: http://localhost:8080/apis/reds
  scsd_base_url: http://localhost:8080/apis/scsd # TODO
  sls_base_url: http://localhost:8080/apis/sls