name: Nightly Integration
on:
  workflow_dispatch:
  pull_request:
  schedule:
  - cron: '0 8 * * *' # 8am every day UTC. 3 AM Central. This will trigger the action to run after the hms-build-workflow-dispatcher has rebuilt HMS images

permissions: read-all

jobs:
  determine-service-versions:
    name: Determine service versions
    runs-on: ubuntu-latest
    outputs:
      csm-releases: ${{ steps.extract-container-images.outputs.csm-releases }}
      images-by-csm-release: ${{ steps.extract-container-images.outputs.images-by-csm-release }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install python dependencies
      shell: bash
      run: pip3 install -r requirements.txt

    - name: Extract container images from CSM manifests
      shell: bash
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARTIFACTORY_ALGOL60_READONLY_USERNAME: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_USERNAME }}
        ARTIFACTORY_ALGOL60_READONLY_TOKEN: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_TOKEN }}
      run: |
        set -eux
        ./csm_manifest_extractor.py

    - name: Add bleeding-edge release
      shell: bash
      # TODO the idea of this would be to gather the latest of all HMS charts regardless if they are in a manifest or not
      # Also this logic can be used for testing to specify images that are not present in a CSM manifest  
      run: |
        cat <<EOF > unstable_images.json
        {
          "unstable": {
              "artifactory.algol60.net/csm-docker/unstable/cray-capmc-hmth-test": [
                "2.7.0-20230112162833.6112bb4"
              ],
              "artifactory.algol60.net/csm-docker/unstable/cray-bss-hmth-test": [
                "1.22.0-20230112162618.c1b4798"
              ],
              "artifactory.algol60.net/csm-docker/unstable/cray-sls-hmth-test": [
                "2.0.0-20230112162714.aaeddf6"
              ],
              "artifactory.algol60.net/csm-docker/unstable/cray-smd-hmth-test": [
                "2.2.0-20230112162745.ca65b47"
              ]
          }
        }
        EOF

        # Merge images
        jq -s '.[0] * .[1]' extractor-output-images_by_csm_release.json unstable_images.json > images_temp.json
        mv images_temp.json extractor-output-images_by_csm_release.json
        

    - name: Save outputs
      shell: bash
      id: extract-container-images # TODO use a better name
      run: |
        echo "images-by-csm-release=$(cat extractor-output-images_by_csm_release.json | jq -c)" >> $GITHUB_OUTPUT
        echo "csm-releases=$(cat extractor-output-images_by_csm_release.json | jq '. | keys' -c)" >> $GITHUB_OUTPUT
  
  integration-test:
    name: Integration test
    needs: determine-service-versions
    strategy:
      matrix:
        csm-release: ${{ fromJSON(needs.determine-service-versions.outputs.csm-releases) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout hms-simulation-environment
      uses: actions/checkout@v3
      with:
        path: hms-simulation-environment
        repository: Cray-HPE/hms-simulation-environment
        ref: v1
        fetch-depth: 0

    - name: Store test data
      shell: bash
      env:
        IMAGES_BY_CSM_RELEASE: ${{ needs.determine-service-versions.outputs.images-by-csm-release }}
      run: |
        echo "CSM Branch: ${{ matrix.csm-release }}"
        echo "Images by csm release:"
        printenv IMAGES_BY_CSM_RELEASE > images-by-csm-release.json
        jq . images-by-csm-release.json

    # Update container images in docker-compose.yaml
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install python dependencies
      shell: bash
      run: pip3 install -r requirements.txt

    - name: Update container images in docker-compose.yaml
      shell: bash
      env:
        CSM_RELEASE: "${{ matrix.csm-release }}"
      run: |
        ./update_docker_compose.py \ 
          --images-by-csm-release images-by-csm-release.json \
          --csm-release "${CSM_RELEASE}" \
          --docker-compose-file ./hms-simulation-environment/docker-compose.yaml

    # Stand up hms-simulation environment
    - name: Standup simulation environment
      shell: bash
      run: |
        set -ex
        cd hms-simulation-environment
        # For debugging output the modified docker-compose compose file
        echo "Updated docker-compose.yaml"
        cat docker-compose.yaml
        # Setup python virtual environment
        ./setup_venv.sh
        . ./venv/bin/activate
        ./run.py configs/sls/small_mountain.json

    # Run tests
    - name: Run tests
      shell: bash
      env:
        CSM_RELEASE: "${{ matrix.csm-release }}"
      run: |
        ./run_tests.py \
          --images-by-csm-release-json images-by-csm-release.json \
          --csm-release "${CSM_RELEASE}" \
          --fix-allure-dir-perms

    - name: Create test results tarball
      id: tarball 
      shell: bash
      run: |
        tar -cvf "allure-results.tar" ./allure  

    - name: Determine artifact name
      id: artifact 
      shell: bash
      env: 
        CSM_RELEASE: ${{ matrix.csm-release }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        set -x
        REPORT_NAME=$(gdate "+%Y-%m-%d_%H-%M-%S") 
        mv allure "${REPORT_NAME}"

        tar -cvf "allure-results.tar" ./"${REPORT_NAME}"

        echo "name=allure-results-${GITHUB_RUN_ID}_$(echo $CSM_RELEASE | tr / -)" >> $GITHUB_OUTPUT

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.artifact.outputs.name }}
        path: allure-results.tar
        retention-days: 1

  generate-reports:
    name: Generate reports
    needs: integration-test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write

    steps:
    - name: Get Github pages site
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Download Allure
      shell: bash
      env:
        ALLURE_VERSION: 2.20.1
      run: |
        set -ex
        wget "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-{ALLURE_VERSION}.tgz"
        tar -xvf "allure-commandline-${ALLURE_VERSION}.tgz"
        mv allure-${ALLURE_VERSION} allure-commandline

    - uses: actions/download-artifact@v3
      with:
        path: artifacts


    - name: Extract artifacts
      shell: bash
      run: | 
        ls artifacts

    # - name: Allure Report action from marketplace
    #   uses: simple-elf/allure-report-action@master
    #   if: always()
    #   id: allure-report
    #   with:
    #     # TODO does this encode branch info?
    #     allure_results: ./allure-agg
    #     gh_pages: gh-pages
    #     allure_report: allure-report
    #     allure_history: allure-history

    # - name: Deploy report to Github Pages
    #   if: always()
    #   uses: peaceiris/actions-gh-pages@v2
    #   env:
    #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: allure-history

    # Deploy into separate directories with timestamp/branch
    # Prune old directories
    # Perhaps collect results from the matrix-jobs and then update github pages at the same time
    # Also do an amend commit to keep the repo small. 
    # Job summary link to github pages
    # If no artifact for job run, then report that an issue occured in the job
    # Root webpage should show the following
    # - Table of links to the last runers sorted by release branch. Date on the right, and columns for each CSM release
    #   Each cell should have a count of passed/failed tests. 
    # - Top of the page should show the status of the last test runs.